# Generated by Django 5.1.7 on 2025-03-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchapp', '0002_complaintmodel'),
        ('userapp', '0002_accountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.accountmodel')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branchapp.branchmodel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
    ]
