# Generated by Django 5.1.7 on 2025-03-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_loanmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('relationship', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('embedding', models.BinaryField()),
                ('account_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
    ]
