# Generated by Django 5.1.7 on 2025-03-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_transactionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('reply', models.TextField(null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
    ]
